#!/bin/bash

# debug option
if [[ $# -eq 2 && $1 == "-d" ]]; then
  # clean compilation
  make clean; make
  gdb --args ./3600dns $2
elif [[ $# -eq 2 && $1 == "-s" ]]; then
  make clean; make
	echo "MINE:" && echo
	./3600dns $2
	echo "SOLUTION:" && echo
	/course/cs3600f14/code/solutions/project3/3600dns $2
elif [[ $# -eq 1 ]]; then
  # clean compilation
  make clean; make
	./3600dns $1
fi

